[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "delegation-framework/=lib/delegation-framework/src/"]
cache_path = "cache"
force = false
optimizer = true
optimizer_runs = 200
via_ir = false
auto_detect_remappings = true

[profile.ci]
fuzz = { runs = 1000 }
